### PR TITLE
CH340G Usb-to-Serial support (Arduino-based clones)

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
Hey @xxxajk, since there seems to be more active development in this fork, I'd like to merge @ideniden's modifications to Physicaloid which [makes it support CH340G](https://github.com/ksksue/PhysicaloidLibrary/issues/30) USB-to-Serial chips. These chips are used in a lot of Arduino-based clones.

That way, when [your pull-request](https://github.com/ksksue/PhysicaloidLibrary/pull/17) merges into the main branch (hopefully soon), we'd already have CH340G support.

Of course, @ideniden's code seems to need a bit of refactoring, so if you've got some time on hand, merging and cleaning those are much appreciated.

Thanks for your time!

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
My apologies, but there seems to be a problem with @ideniden's implementation:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
    at com.physicaloid.lib.usb.driver.uart.UartCH340.setBaudrate(UartCH340.java:151)
    at com.physicaloid.lib.usb.driver.uart.UartCH340.setUartConfig(UartCH340.java:106)
    at com.physicaloid.lib.framework.Uploader.upload(Uploader.java:47)
    at com.physicaloid.lib.Physicaloid$1.run(Physicaloid.java:417)
```

I'm sorry for opening this pull request, it needs to be delayed until this problem is sorted out.

**Comment by xxxajk** [comment]
That would be extremely cool. Can you resolve the conflicts?

**Comment by xxxajk** [comment]
Also, please note that I do not use any of the gradle stuff, so I don't maintain any of it. 
I use Apache ant for building on classic android setup. 
So if there is anything that needs to be changed/added there to add in the new stuff I put in, I'm ignorant if it has any adverse effects.

**Comment by xxxajk** [comment]
Broken, besides I have written my own.

**Pull request closed without merging**
