### PR TITLE
Added automatic build & upload with Travis CI

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
## Automatic Ant builds with [Travis CI](https://travis-ci.org/) and upload to File.io
up-ci

### Descripiton
With this PR, the project can be built automatically with Ant, using [Travis CI](https://travis-ci.org/). After each successful build, the generated `.apk` file is uploaded to [`file.io`](https://file.io) with an expiration date of 1 month.

That way, the user wouldn't need to necessary clone the repo and launch NetBeans (or use Ant within CLI) to build the project.

### Installation
1. Step one: https://travis-ci.org/getting_started
Sign-in with your GitHub account and activate the repo

2. Accept and merge this PR.
The required `.travis.yml` file is already in here.

### Usage
- After each commit/PR, the CI will automatically fetch the repo, build it and upload the result
- If an APK file is needed, the file can be simply downloaded from the generated `file.io` link.

<hr>
This can also be used to track and test the codebase to make sure there are no errors in the project.

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
**Demo:** https://travis-ci.com/DRSDavidSoft/PhysicaloidLibrary/jobs/138246598
(Scroll to the end for the generated link.)

On my machine, I use the following to then automatically install the generated `.apk` file:
(The mobile phone is connected wirelessly with adb)

```
adb connect 192.168.1.114
curl https://file.io/<link_id>
adb install -R ./result.apk
```

**Comment by xxxajk** [comment]
Thanks!!! I'll further update the readme if you think necessary, WCH is short for "winchiphead", the producer of the chip.

**Comment by DRSDavidSoft** [comment]
@xxxajk Hmm, interesting, I always wondered what that meant, especially since many referred to them as "QinHeng".

I give a 👍 for any amount of `README` and other docs updates; it's getting a bit old at this stage.

**Comment by xxxajk** [comment]
http://www.winchiphead.com/
Nanjing QinHeng Electronics Co.,Ltd.
:-)

**Pull request merged**
